url: https://y7kim.github.io
baseurl:

# Site settings
title: Clara Ferro
email: claraferro18@gmail.com
description: "Sono un'artista, un'apprendista tatuatrice e sto studiando la programmazione Front End da autodidatta. Se i miei lavori ti piacciono contattami e accomodati sulla mia sedia, vediamo di scolpire qualcosa anche sulla TUA pelle!"

instagram_link: <a href="https://www.instagram.com/claravoyant_ink/">Instagram @claravoyant_ink</a> 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/claravoyant_ink/
  - title: facebook
    url: https://www.facebook.com/profile.php?id=100008368982457
  - title: github
    url: https://github.com/claraferro
  - title: linkedin
    url: https://www.linkedin.com/in/clara-ferro

# Build settings
markdown: kramdown
permalink: pretty